---
  - name: Ansible Playbook
    hosts: all
    become: true
    tasks:
      - name: Update cache 
        apt:
          update_cache: yes
      - name: install some plugin
        apt: 
         name: ['apt-transport-https', 'ca-certificates']
         state: absent
         update_cache: yes
        
  # - hosts: master
  #   become: true
  #   gather_facts: false
  #   tasks:
  #     - name: get join command
  #       shell: echo 'join token'
  #       register: join_command_raw

  #     - name: set join command
  #       set_fact:
  #         join_command: "{{ join_command_raw.stdout_lines[0] }}"

  # - hosts: nodes
  #   become: true
  #   tasks:
  #     - name: join cluster
  #       shell: "{{ hostvars['master'].join_command }} >> node_joined.txt"
  #       args:
  #         chdir: $HOME
  #         creates: node_joined.txt
        


      