---
  - name: Ansible Playbook
    hosts: all
    become: true
    tasks:
      - name: Update cache 
        apt:
          update_cache: yes
          cache_valid_time: 3600
      - name: install net-tools
        apt: name=net-tools state=absent
      